services:
  - type: web
    name: genre-discovery
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn genre_discovery.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
