# Generated by Django 4.2.30 on 2026-05-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tag_type', models.CharField(choices=[('genre', 'Genre'), ('freeform', 'Freeform')], default='freeform', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cloudcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('quality_score', models.FloatField(default=0.0)),
                ('publish_date', models.DateTimeField()),
                ('play_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('picture_url', models.URLField(blank=True, default='')),
                ('listeners', models.ManyToManyField(blank=True, related_name='listened_cloudcasts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudcasts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='cloudcasts', to='cloudcasts.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
                'unique_together': {('owner', 'slug')},
            },
        ),
    ]
